import React, { useEffect, useState } from 'react';
import { FeesAPI } from '../../../services/feesApiService';

export default function Receipts() {
  const [data, setData] = useState([]);
  const [count, setCount] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [filters, setFilters] = useState({ is_printed: '', generated_by: '', search: '', ordering: '-generated_date', page: 1 });

  const fetchData = async () => {
    setLoading(true); setError(null);
    try {
      const res = await FeesAPI.listReceipts(filters);
      const items = Array.isArray(res?.results) ? res.results : Array.isArray(res) ? res : [];
      setData(items);
      setCount(res?.count ?? items.length);
    } catch (e) { setError(e.data || e.message); }
    finally { setLoading(false); }
  };

  useEffect(() => { const t = setTimeout(fetchData, 300); return () => clearTimeout(t); }, [filters]);

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-2 items-end">
        <div>
          <label className="block text-sm text-gray-600">Printed</label>
          <select className="border rounded px-2 py-1" value={filters.is_printed}
                  onChange={e => setFilters(f => ({ ...f, is_printed: e.target.value, page: 1 }))}>
            <option value="">All</option>
            <option value="true">Printed</option>
            <option value="false">Unprinted</option>
          </select>
        </div>
        <div>
          <label className="block text-sm text-gray-600">Generated By (ID)</label>
          <input className="border rounded px-2 py-1" value={filters.generated_by}
                 onChange={e => setFilters(f => ({ ...f, generated_by: e.target.value, page: 1 }))} />
        </div>
        <div>
          <label className="block text-sm text-gray-600">Search</label>
          <input className="border rounded px-2 py-1" value={filters.search}
                 onChange={e => setFilters(f => ({ ...f, search: e.target.value, page: 1 }))} />
        </div>
        <div>
          <label className="block text-sm text-gray-600">Ordering</label>
          <select className="border rounded px-2 py-1" value={filters.ordering}
                  onChange={e => setFilters(f => ({ ...f, ordering: e.target.value }))}>
            <option value="-generated_date">Generated (desc)</option>
            <option value="generated_date">Generated</option>
            <option value="printed_date">Printed</option>
            <option value="created_at">Created</option>
          </select>
        </div>
        <button className="ml-auto bg-blue-600 text-white px-3 py-2 rounded" onClick={fetchData}>Refresh</button>
      </div>

      {error && <div className="text-red-600 text-sm">{String(error)}</div>}
      {loading ? <div>Loading...</div> : (
        <div className="overflow-auto">
          <table className="min-w-full border">
            <thead>
              <tr className="bg-gray-50">
                <th className="p-2 border">Receipt #</th>
                <th className="p-2 border">Student</th>
                <th className="p-2 border">Payment</th>
                <th className="p-2 border">Generated</th>
                <th className="p-2 border">Printed</th>
                <th className="p-2 border">Printed?</th>
                <th className="p-2 border">Actions</th>
              </tr>
            </thead>
            <tbody>
              {data.map(row => (
                <tr key={row.id}>
                  <td className="p-2 border">{row.receipt_number}</td>
                  <td className="p-2 border">{row.student_label || row.student_fee?.student?.roll_number}</td>
                  <td className="p-2 border">{row.payment_id}</td>
                  <td className="p-2 border">{row.generated_date}</td>
                  <td className="p-2 border">{row.printed_date}</td>
                  <td className="p-2 border">{String(row.is_printed)}</td>
                  <td className="p-2 border space-x-2">
                    {!row.is_printed && (
                      <button className="px-2 py-1 text-xs bg-green-600 text-white rounded"
                              onClick={async () => { await FeesAPI.markReceiptPrinted(row.id); fetchData(); }}>
                        Mark Printed
                      </button>
                    )}
                    <button className="px-2 py-1 text-xs bg-gray-700 text-white rounded"
                            onClick={async () => { const r = await FeesAPI.downloadReceipt(row.id); alert(r?.message || 'Downloaded (placeholder)'); }}>
                      Download
                    </button>
                  </td>
                </tr>
              ))}
              {data.length === 0 && (
                <tr><td className="p-4 text-center" colSpan={7}>No data</td></tr>
              )}
            </tbody>
          </table>
          <div className="flex items-center justify-between mt-2 text-sm text-gray-600">
            <div>Total: {count}</div>
            <div className="space-x-2">
              <button className="px-2 py-1 border rounded" disabled={filters.page <= 1}
                      onClick={() => setFilters(f => ({ ...f, page: Math.max(1, (f.page || 1) - 1) }))}>Prev</button>
              <button className="px-2 py-1 border rounded"
                      onClick={() => setFilters(f => ({ ...f, page: (f.page || 1) + 1 }))}>Next</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}


